import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "@/components/providers";
import { Playfair_Display } from "next/font/google";
import { auth } from "@/auth";
import "./globals.css";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Jobjobs",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session);
  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            "flex min-h-screen flex-col",
            geistSans.variable,
            geistMono.variable,
            playfair.variable,
          )}
        >
          <Providers>{children}</Providers>
        </body>
      </html>
    </SessionProvider>
  );
}
